version: '3.1'
services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql-data2:/var/lib/mysql

# Comment until your ASP.NET CORE are ready
#  app:
#    image: mcr.microsoft.com/dotnet/aspnet:5.0
#    container_name: aspnet-app
#    ports:
#      - "80:80"
#    volumes:
#      - ./aspnet-app:/app
#    depends_on:
#      - mysql
#    environment:
#      ASPNETCORE_URLS: http://+:80
#      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=mydb;User=myuser;Password=mypassword"
